export const DISTRICTS = [
  { id: 1, name: "Bukit Merah East" },
  { id: 2, name: "Marina Bay" },
  { id: 3, name: "Rochor" },
  { id: 4, name: "Bukit Merah West" },
  { id: 5, name: "Clementi" },
  { id: 6, name: "Jurong East" },
  { id: 7, name: "Queenstown" },
  { id: 8, name: "Bishan" },
  { id: 9, name: "Bukit Timah" },
  { id: 10, name: "Kampong Java" },
  { id: 11, name: "Orchard" },
  { id: 12, name: "Toa Payoh" },
  { id: 13, name: "Ang Mo Kio North" },
  { id: 14, name: "Ang Mo Kio South" },
  { id: 15, name: "Hougang" },
  { id: 16, name: "Punggol" },
  { id: 17, name: "Sengkang" },
  { id: 18, name: "Serangoon" },
  { id: 19, name: "Woodleigh" },
  { id: 20, name: "Bedok" },
  { id: 21, name: "Changi" },
  { id: 22, name: "Geylang" },
  { id: 23, name: "Marine Parade" },
  { id: 24, name: "Pasir Ris" },
  { id: 25, name: "Tampines" },
  { id: 26, name: "Bukit Batok" },
  { id: 27, name: "Bukit Panjang" },
  { id: 28, name: "Choa Chu Kang" },
  { id: 29, name: "Jurong West" },
  { id: 30, name: "Nanyang" },
  { id: 31, name: "Woodlands East" },
  { id: 32, name: "Woodlands West" },
  { id: 33, name: "Yishun North" },
  { id: 34, name: "Yishun South" },
  { id: 35, name: "Sembawang" },
  { id: 36, name: "Checkpoint" },
] as const

export type District = (typeof DISTRICTS)[number]
