export const DISTRICTS = [
  { id: 1, name: "District 1 - Boat Quay / Raffles Place / Marina" },
  { id: 2, name: "District 2 - Chinatown / Tanjong Pagar" },
  { id: 3, name: "District 3 - Alexandra / Commonwealth" },
  { id: 4, name: "District 4 - Harbourfront / Telok Blangah" },
  { id: 5, name: "District 5 - Buona Vista / West Coast / Clementi" },
  { id: 6, name: "District 6 - City Hall / Clarke Quay" },
  { id: 7, name: "District 7 - Beach Road / Bugis / Rochor" },
  { id: 8, name: "District 8 - Farrer Park / Serangoon Road" },
  { id: 9, name: "District 9 - Orchard / River Valley" },
  { id: 10, name: "District 10 - Tanglin / Holland" },
  { id: 11, name: "District 11 - Newton / Novena" },
  { id: 12, name: "District 12 - Balestier / Toa Payoh" },
  { id: 13, name: "District 13 - Macpherson / Potong Pasir" },
  { id: 14, name: "District 14 - Eunos / Geylang / Paya Lebar" },
  { id: 15, name: "District 15 - East Coast / Marine Parade" },
  { id: 16, name: "District 16 - Bedok / Upper East Coast" },
  { id: 17, name: "District 17 - Changi Airport / Changi Village" },
  { id: 18, name: "District 18 - Pasir Ris / Tampines" },
  { id: 19, name: "District 19 - Hougang / Punggol / Sengkang" },
  { id: 20, name: "District 20 - Ang Mo Kio / Bishan" },
  { id: 21, name: "District 21 - Clementi Park / Upper Bukit Timah" },
  { id: 22, name: "District 22 - Boon Lay / Jurong / Tuas" },
  { id: 23, name: "District 23 - Dairy Farm / Bukit Panjang / Choa Chu Kang" },
  { id: 24, name: "District 24 - Lim Chu Kang / Tengah" },
  { id: 25, name: "District 25 - Admiralty / Woodlands" },
  { id: 26, name: "District 26 - Mandai / Upper Thomson" },
  { id: 27, name: "District 27 - Sembawang / Yishun" },
  { id: 28, name: "District 28 - Seletar / Yio Chu Kang" },
  { id: 29, name: "District 29 - Serangoon Garden" },
  { id: 30, name: "District 30 - Loyang / Tampines" },
  { id: 31, name: "District 31 - Katong / Joo Chiat" },
  { id: 32, name: "District 32 - Bedok South" },
  { id: 33, name: "District 33 - Clementi Woods" },
  { id: 34, name: "District 34 - Springleaf" },
  { id: 35, name: "District 35 - Hillview / Dairy Farm" },
  { id: 36, name: "District 36 - Keat Hong" },
  { id: 37, name: "District 37 - Bukit Batok" },
  { id: 38, name: "District 38 - Jurong East" },
  { id: 39, name: "District 39 - Jurong West" },
  { id: 40, name: "District 40 - Boon Lay" },
  { id: 41, name: "District 41 - Tuas" },
] as const

export type District = (typeof DISTRICTS)[number]
